# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: AUTO_TASK_FOR_BILIBILI

on:
  push:
    branches: main
  pull_request:
    branches: main
  workflow_dispatch:
  schedule:
    - cron: '30 10 * * *'
    # cron表达式，Actions时区是UTC时间，所以下午18点要往前推8个小时


jobs:
  start:

    runs-on: ubuntu-latest

    steps:
      - name: Validation parameters
        env:
          BILI_JCT: ${{ secrets.BILI_JCT }}
          DEDEUSERID: ${{ secrets.DEDEUSERID }}
          SESSDATA: ${{ secrets.SESSDATA }}
          TZ: Asia/Shanghai
          # 时区配置为Asia/Shanghai
        run: |
          if [[ -z '${{ secrets.SESSDATA }}' ]]
          then
              echo "Secrets中SESSDATA参数未填写，请填写后重试"
              exit -1
          fi
          if [[ -z '${{ secrets.BILI_JCT }}' ]]
          then
              echo "Secrets中BILI_JCT参数未填写，请填写后重试"
              exit -1
          fi
          if [[ -z '${{ secrets.DEDEUSERID }}' ]]
          then
              echo "Secrets中DEDEUSERID参数未填写，请填写后重试"
              exit -1
          fi
          ret=`wget --header="Cookie: SESSDATA=${{ secrets.SESSDATA }}" -q -O - https://api.bilibili.com/x/web-interface/nav`
          if [[ ! $ret =~ '"isLogin":true' ]]
          then
              if [[ -n '${{ secrets.SCKEY }}' ]]
              then
                  wget -q -O - "http://sc.ftqq.com/${{ secrets.SCKEY }}.send?text=%e6%82%a8%e7%9a%84B%e7%ab%99cookie%e5%a4%b1%e6%95%88%e8%be%a3%ef%bc%8c%e5%bf%ab%e5%8e%bb%e9%87%8d%e6%96%b0%e9%85%8d%e7%bd%ae%e5%93%a6%7e"
              fi
              echo "账号登录状态已过期，请重新配置"
              exit -1
          fi
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build with Maven
        env:
          BILI_JCT: ${{ secrets.BILI_JCT }}
          DEDEUSERID: ${{ secrets.DEDEUSERID }}
          SESSDATA: ${{ secrets.SESSDATA }}
          TZ: Asia/Shanghai
          # 时区配置为Asia/Shanghai
        run: |
          mvn compile exec:java -Dexec.mainClass="top.misec.BiliMain" -Dexec.args="${DEDEUSERID} ${SESSDATA} ${BILI_JCT}"
